version: '3.8'

services:
  # PMS MCP Server
  mcp-server:
    build: ./agent/pms_mcp_server
    container_name: pms-mcp-server
    ports:
      - "3001:3001"
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=3001
      - PMS_API_URL=${PMS_API_URL:-https://api-dev.botel.ai}
      - PMS_API_KEY=${PMS_API_KEY}
    volumes:
      - ./agent/pms_mcp_server/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # LiveKit Agent
  livekit-agent:
    build: ./agent
    container_name: livekit-agent
    depends_on:
      mcp-server:
        condition: service_healthy
    environment:
      # LiveKit Configuration
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      
      # AI Services
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ASSEMBLYAI_API_KEY=${ASSEMBLYAI_API_KEY}
      - CARTESIA_API_KEY=${CARTESIA_API_KEY}
      
      # Azure OpenAI
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - AZURE_OPENAI_DEPLOYMENT_NAME_MINI=${AZURE_OPENAI_DEPLOYMENT_NAME_MINI}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      
      # MCP Server Configuration
      - PMS_MCP_SERVER_URL=http://mcp-server:3001
      - PMS_MCP_SERVER_TOKEN=${PMS_MCP_SERVER_TOKEN}
      
      # Optional Services
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    volumes:
      - ./agent/logs:/app/logs
    restart: unless-stopped
    networks:
      - default

  # Frontend (optional - for full stack local development)
  frontend:
    build: ./frontend
    container_name: livekit-frontend
    ports:
      - "3000:3000"
    environment:
      - LIVEKIT_URL=${LIVEKIT_URL}
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    restart: unless-stopped
    profiles:
      - fullstack

networks:
  default:
    driver: bridge

volumes:
  mcp-logs:
  agent-logs: