name: Build and deploy container app to Azure Web App - livekitsdr-agent

on:
  push:
    branches:
      - main
    paths:
      - 'agent/**'
      - '.github/workflows/azure-agent.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: livekitsdracr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: livekitsdracr.azurecr.io/livekitsdr-agent:${{ github.sha }}
          file: ./agent/Dockerfile
          context: ./agent

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'livekitsdr-agent'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_AGENT }}
          images: 'livekitsdracr.azurecr.io/livekitsdr-agent:${{ github.sha }}'