name: Build and deploy container app to Azure Web App - livekitsdr-agent

on:
  push:
    branches:
      - main
    paths:
      - 'agent/**'
      - '.github/workflows/azure-agent.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://livekitsdr.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_c99540fac0be454db960b97bc7beaf5e }}
          password: ${{ secrets.AzureAppService_ContainerPassword_d3fc1b54ffc5477c9b672e8f84b10a0f }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: livekitsdr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c99540fac0be454db960b97bc7beaf5e }}/livekitsdr-agent:${{ github.sha }}
          file: ./agent/Dockerfile
          context: ./agent

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'livekitsdr-agent'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_5fbe93e9f9b24e01852fb7ce99dedd1f }}
          images: 'livekitsdr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_c99540fac0be454db960b97bc7beaf5e }}/livekitsdr-agent:${{ github.sha }}'